# Generated by Django 3.2.7 on 2022-06-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0006_auto_20220605_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followingcount',
            name='following_user_name',
        ),
        migrations.AddField(
            model_name='followingcount',
            name='following_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
