# Generated by Django 3.2.7 on 2022-06-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='username', max_length=200),
            preserve_default=False,
        ),
    ]
