# Generated by Django 3.2.7 on 2022-06-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0009_comment_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted_by',
            new_name='commented_by',
        ),
    ]
